---

- name: Copy daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: add cgroup configs to /boot/firmware/cmdline.txt
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc'
    line: 'net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1'
    owner: root
    group: root
    mode: 0755

- name: Copy k8s.conf
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: apply sysctl
  shell: sysctl --system
  args:
    executable: /bin/bash

- name: Install k8s apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: install k8s repo
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: k8s

- name: install packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: apt-mark hold
  shell: apt-mark hold kubelet kubeadm kubectl
  args:
    executable: /bin/bash

...
