---

- name: Copy TOKEN to /opt/TOKEN
  copy:
    src: out/TOKEN
    dest: /opt/TOKEN

- name: Copy CERTIFICATE_KEY to /opt/CERTIFICATE_KEY
  copy:
    src: out/CERTIFICATE_KEY
    dest: /opt/CERTIFICATE_KEY

- name: Copy CA_KEY_HASH to /opt/CA_KEY_HASH
  copy:
    src: out/CA_KEY_HASH
    dest: /opt/CA_KEY_HASH

- name: check if kubelet is intalled / worker has joined
  stat:
    path: /var/lib/kubelet/config.yaml
  register: _kubelet_stat

- name: include worker tasks if kubectl_server return does not equal 0 (is error)
  include: worker.yml
  when: not _kubelet_stat.stat.exists

...
