---

- hosts: all
  become: true
  become_method: sudo

  roles:
  - andrelohmann.root_colored_prompt
  - andrelohmann.kubectl
  - ssh_key

  tasks:
  - name: install ansible-galaxy roles
    shell: ansible-galaxy install -r requirements.yml
    args:
      executable: /bin/bash
      chdir: /home/vagrant/ansible
    become: yes
    become_user: vagrant

  - name: Create .kube folder
    file:
      state: directory
      path: /home/vagrant/.kube
      owner: vagrant
      group: vagrant
      mode: 0755

...
