---

- hosts: all
  become: true
  become_method: sudo

  #vars:
  #  some_var: some_value

  roles:
  - andrelohmann.root_colored_prompt
  - andrelohmann.kubectl
  - ssh_key

  tasks:
  - name: install ansible-galaxy roles
    shell: ansible-galaxy install -r requirements.yml
    args:
      executable: /bin/bash
      chdir: /home/vagrant/ansible
    become: yes
    become_user: vagrant

...
