---

- hosts: worker
  become: true
  become_method: sudo

  roles:
  - k8s_worker_destroy
  - k8s_uninstall

- hosts: master
  become: true
  become_method: sudo

  roles:
  - k8s_master_destroy
  - k8s_uninstall

...
