---

- hosts: all
  become: true
  become_method: sudo

  roles:
  - andrelohmann.root_colored_prompt
  - update_upgrade

- hosts: k8s
  become: true
  become_method: sudo

  vars:
    some_var: some_value

  roles:
  - andrelohmann.docker
  - rpi_k8s_install

...
