iptables:
  router: True  # True if forwarding needs to be allowed
  pingables:  # hosts, that are allowed to ping the target
  - host: proxy.k8s.lan
    ip: 192.168.199.10
  - host: master1.k8s.lan
    ip: 192.168.199.11
  - host: master2.k8s.lan
    ip: 192.168.199.12
  - host: master3.k8s.lan
    ip: 192.168.199.13
  - host: worker1.k8s.lan
    ip: 192.168.199.21
  - host: worker2.k8s.lan
    ip: 192.168.199.22
  - host: worker3.k8s.lan
    ip: 192.168.199.23
  custom_pre_rules: [] # add custom rules
  chains:
  - name: APIServer
    comment: "Kubernetes API server"
    protocol: tcp  # tcp/icmp/udp
    ports:
    - 6443
  - name: ControlPlane
    comment: "Kubelet"
    protocol: tcp  # tcp/icmp/udp
    ports:
    - 10250
    - 10251
    - 10252
    sources:
    - host: proxy.k8s.lan
      ip: 192.168.199.10
    - host: master1.k8s.lan
      ip: 192.168.199.11
    - host: master2.k8s.lan
      ip: 192.168.199.12
    - host: master3.k8s.lan
      ip: 192.168.199.13
  - name: etcd
    comment: "etcd server client API"
    protocol: tcp # tcp/icmp/udp
    ports:
    - 2379:2380
    sources:
    - host: master1.k8s.lan
      ip: 192.168.199.11
    - host: master2.k8s.lan
      ip: 192.168.199.12
    - host: master3.k8s.lan
      ip: 192.168.199.13
  - name: CalicoBGP
    comment: "Calico networking (BGP)"
    protocol: tcp  # tcp/icmp/udp
    ports:
    - 179
  custom_post_rules: []
